"""add_klarna_order_id

Revision ID: d4e9ba7dd8ca
Revises: 0002
Create Date: 2026-04-15 14:39:40.939540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e9ba7dd8ca'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('klarna_order_id', sa.String(length=255), nullable=True))
    op.drop_constraint('payments_swish_reference_key', 'payments', type_='unique')
    op.drop_column('payments', 'swish_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('swish_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('payments_swish_reference_key', 'payments', ['swish_reference'])
    op.drop_column('payments', 'klarna_order_id')
    # ### end Alembic commands ###
